/* eslint-disable import/prefer-default-export */
export const MessageSeed = [
  {
    scheduleId: 1,
    userId: 1,
    message: 'lee',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    scheduleId: 1,
    userId: 1,
    message: 'ges',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    scheduleId: 1,
    userId: 1,
    message: 'tes',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    scheduleId: 1,
    userId: 1,
    message: 'hfds',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    scheduleId: 1,
    userId: 1,
    message: 'lee',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    scheduleId: 1,
    userId: 1,
    message: 'lee',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    scheduleId: 1,
    userId: 1,
    message: 'dsagds',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    scheduleId: 1,
    userId: 1,
    message: 'eher',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    scheduleId: 1,
    userId: 1,
    message: 'adhfdah',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    scheduleId: 1,
    userId: 1,
    message: 'hfdahfad',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    scheduleId: 1,
    userId: 1,
    message: 'ryjrtje',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    scheduleId: 1,
    userId: 1,
    message: 'jertjtr',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    scheduleId: 1,
    userId: 1,
    message: 'ghfdgfds',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    scheduleId: 1,
    userId: 1,
    message: 'jgfdjfd',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    scheduleId: 1,
    userId: 1,
    message: 'hfdshfds',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    scheduleId: 1,
    userId: 1,
    message: 'hehw',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    scheduleId: 1,
    userId: 1,
    message: 'dudsu',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    scheduleId: 1,
    userId: 1,
    message: 'cnbvnbv',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    scheduleId: 1,
    userId: 1,
    message: 'nbvcnbvc',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    scheduleId: 1,
    userId: 1,
    message: 'hfdshfds hfdshdf',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    scheduleId: 1,
    userId: 1,
    message: 'uduyfsu dsgfudfs',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    scheduleId: 1,
    userId: 1,
    message: 'eueruer',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
];
